Failure # 1 (occurred at 2020-12-13_06-40-24)
Traceback (most recent call last):
  File "/home/zack/github/595_EECS_final_project/csqa/venv/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 726, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/zack/github/595_EECS_final_project/csqa/venv/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 489, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/zack/github/595_EECS_final_project/csqa/venv/lib/python3.8/site-packages/ray/worker.py", line 1452, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TuneError): [36mray::ImplicitFunc.train()[39m (pid=864277, ip=192.168.0.191)
  File "python/ray/_raylet.pyx", line 482, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 436, in ray._raylet.execute_task.function_executor
  File "/home/zack/github/595_EECS_final_project/csqa/venv/lib/python3.8/site-packages/ray/tune/trainable.py", line 336, in train
    result = self.step()
  File "/home/zack/github/595_EECS_final_project/csqa/venv/lib/python3.8/site-packages/ray/tune/function_runner.py", line 366, in step
    self._report_thread_runner_error(block=True)
  File "/home/zack/github/595_EECS_final_project/csqa/venv/lib/python3.8/site-packages/ray/tune/function_runner.py", line 512, in _report_thread_runner_error
    raise TuneError(("Trial raised an exception. Traceback:\n{}"
ray.tune.error.TuneError: Trial raised an exception. Traceback:
[36mray::ImplicitFunc.train()[39m (pid=864277, ip=192.168.0.191)
  File "/home/zack/github/595_EECS_final_project/csqa/venv/lib/python3.8/site-packages/ray/tune/function_runner.py", line 248, in run
    self._entrypoint()
  File "/home/zack/github/595_EECS_final_project/csqa/venv/lib/python3.8/site-packages/ray/tune/function_runner.py", line 315, in entrypoint
    return self._trainable_func(self.config, self._status_reporter,
  File "/home/zack/github/595_EECS_final_project/csqa/venv/lib/python3.8/site-packages/ray/tune/function_runner.py", line 575, in _trainable_func
    output = fn()
  File "/home/zack/github/595_EECS_final_project/csqa/pytorch_reimpl.py", line 176, in train_tune
    model = Model(config)
  File "/home/zack/github/595_EECS_final_project/csqa/pytorch_reimpl.py", line 76, in __init__
    hidden_act=self.model_config[
KeyError: 'hidden_dropout_prob'

